#!/usr/bin/env bash
# Anulaciones de #106d-6b: se retira cada mitad de juicio del archivo de credenciales de Anthropic.
set -u
T=${T:-/home/user/thyrox}; cd "$T/src/packages/provider"
AF="src/accounts/imports/anthropicAuthFile.ts"; AI="src/accounts/imports/anthropicAuthImport.ts"
run() { timeout 120 bun test ./__tests__/accounts/imports/anthropicAuthFile.test.ts 2>&1 | gawk '/^\(fail\)|^ *[0-9]+ (pass|fail)$/'; }
source "$T/.claude/workbench/mitm-f7h-api-20260928T070339/annul-lib.sh"
echo "== 1: sin token no se refresca"; annul "$AF" "  if (!toNonEmptyString(connection.accessToken)) return true" "  void 0"
echo "== 2: el margen es estricto"; annul "$AF" "- nowMs <= REFRESH_MARGIN_MS" "- nowMs < REFRESH_MARGIN_MS"
echo "== 3: sin caducidad se refresca"; annul "$AF" "  if (!expiresAt) return false" "  if (!expiresAt) return true"
echo "== 4: sin etiqueta por defecto"; annul "$AF" " || 'anthropic-account'" " || ''"
echo "== 5: los guiones de los bordes se quedan"; annul "$AF" ".replace(/^-+|-+\$/g, '')" ""
echo "== 6: los alcances sin filtrar"; annul "$AF" "specific.scopes.filter((scope): scope is string => typeof scope === 'string')" "(specific.scopes as string[])"
echo "== 7: el nivel en blanco se escribe"; annul "$AF" "  if (rateLimitTier) payload.claudeAiOauth.rateLimitTier = rateLimitTier" "  payload.claudeAiOauth.rateLimitTier = rateLimitTier as string"
echo "== 8: cualquier proveedor exporta"; annul "$AF" "  if (connection.provider !== ANTHROPIC_PROVIDER_ID) throw" "  if (false) throw"
echo "== 9: una clave de API exporta"; annul "$AF" "  if (connection.authType !== 'oauth') throw" "  if (false) throw"
echo "== 10: siempre se refresca"; annul "$AF" "  if (!shouldRefreshAnthropicConnection(connection, now())) return connection" "  void 0"
echo "== 11: el refresco irrecuperable es un fallo genérico"; annul "$AF" "  if (refreshed && 'unrecoverable' in refreshed) {" "  if (false) {"
echo "== 12: el refresco no se persiste"; annul "$AF" "  deps.store.update(connectionId, {" "  void ({"
echo "== 13: el refresh token viejo se pierde"; annul "$AF" "refreshToken: toNonEmptyString(refreshed.refreshToken) || refreshToken," "refreshToken: toNonEmptyString(refreshed.refreshToken),"
echo "== 14: los datos del proveedor se reemplazan"; annul "$AF" "{ ...toRecord(connection.providerSpecificData), ...toRecord(refreshed.providerSpecificData) }" "toRecord(refreshed.providerSpecificData)"
echo "== 15: la caducidad no se recalcula"; annul "$AF" "expiresAt: typeof refreshed.expiresIn === 'number' ? new Date(now() + refreshed.expiresIn * MILLISECONDS_PER_SECOND).toISOString() : connection.expiresAt || null," "expiresAt: connection.expiresAt || null,"
echo "== 16: el archivo por la etiqueta"; annul "$AF" "sanitizeFileNamePart(email || connectionLabel)" "sanitizeFileNamePart(connectionLabel)"
echo "== 17: sin copia al lado"; annul "$AF" "    await copyFile(authPath, savedBakPath)" "    void 0"
echo "== 18: lo demás del archivo se pierde"; annul "$AF" "JSON.stringify({ ...existingDoc, claudeAiOauth:" "JSON.stringify({ claudeAiOauth:"
echo "== 19: legible por todos"; annul "$AF" "const OWNER_ONLY = 0o600" "const OWNER_ONLY = 0o644"
echo "== 20: sin informar lo conservado"; annul "$AF" "mcpOAuthPreserved: !!existingDoc.mcpOAuth" "mcpOAuthPreserved: false"
echo "== 21: se importa sin access token"; annul "$AI" "  if (!accessToken) throw" "  if (false) throw"
echo "== 22: se importa sin refresh token"; annul "$AI" "  if (!refreshToken) throw" "  if (false) throw"
echo "== 23: la caducidad numérica queda en milisegundos"; annul "$AI" "expiresAt = new Date(block.expiresAt).toISOString()" "expiresAt = String(block.expiresAt)"
echo "== 24: la caducidad en texto sin recortar"; annul "$AI" "expiresAt = block.expiresAt.trim()" "expiresAt = block.expiresAt"
echo "== 25: los alcances importados sin filtrar"; annul "$AI" "block.scopes.filter((scope): scope is string => typeof scope === 'string')" "(block.scopes as string[])"
echo "== 26: un bootstrap caído rompe la importación"; annul "$AI" "    if (!response.ok) return base" "    void 0"
echo "== 27: el nivel del archivo se pierde"; annul "$AI" "toNonEmptyString(body.rate_limit_tier) || parsed.rateLimitTier" "toNonEmptyString(body.rate_limit_tier)"
echo "== 28: sin correo del bootstrap"; annul "$AI" "email: parsed.email || toNonEmptyString(body.account_email)," "email: parsed.email,"
echo "== 29: la cuenta distingue mayúsculas"; annul "$AI" "?.toLowerCase() === wanted" " === accountUUID"
echo "== 30: el duplicado se sobrescribe solo"; annul "$AI" "      if (!options.overwriteExisting) {" "      if (false) {"
echo "== 31: la identidad de dispositivo se renueva"; annul "$AI" "cliUserID: toNonEmptyString(existingData.cliUserID) || newDeviceId()" "cliUserID: newDeviceId()"
echo "== 32: el nombre existente se pierde"; annul "$AI" "name: options.name || (existing.name as string | undefined) || options.email" "name: options.name || options.email"
echo "== 33: sin identidad se importa"; annul "$AI" "  if (!enriched.email && !enriched.accountUUID && !options.overwriteExisting) {" "  if (false) {"
echo "== 34: sin nombre por defecto"; annul "$AI" "const IMPORTED_NAME = 'Anthropic (imported)'" "const IMPORTED_NAME = ''"
echo "== 35: un fetch que lanza rompe la importación"; annul "$AI" "  } catch {
    return base
  } finally {" "  } finally {"
echo "== restaurado"; git -C "$T" status --short -- src/packages/provider/src/accounts/imports; run
