#!/usr/bin/env bash
# Anulaciones de #106d-6c-2: importación masiva de codex y JSON de sesión.
set -u
T=${T:-/home/user/thyrox}; cd "$T/src/packages/provider"
BI="src/accounts/imports/codexBulkImport.ts"; SI="src/accounts/imports/codexSessionImport.ts"
run() { timeout 120 bun test ./__tests__/accounts/imports/codexBulkImport.test.ts 2>&1 | gawk '/^\(fail\)|^ *[0-9]+ (pass|fail)$/'; }
source "$T/.claude/workbench/mitm-f7h-api-20260928T070339/annul-lib.sh"
echo "== 1: el plan no se lee del token"; annul "$BI" "chatgptPlanType: text(chatgpt.chatgpt_plan_type)" "chatgptPlanType: undefined"
echo "== 2: sin recortar el correo"; annul "$BI" "if (typeof candidate === 'string' && candidate.trim()) return candidate.trim()" "if (typeof candidate === 'string' && candidate.trim()) return candidate"
echo "== 3: la caducidad declarada no gana"; annul "$BI" "const expiresAt = parseExpiry(record.expired) ?? accessTokenExpiry(accessToken, nowMs)" "const expiresAt = accessTokenExpiry(accessToken, nowMs)"
echo "== 4: una caducidad ilegible pasa"; annul "$BI" "  return Number.isFinite(ms) ? new Date(ms).toISOString() : undefined" "  return Number.isFinite(ms) ? new Date(ms).toISOString() : value"
echo "== 5: sin diez días por defecto"; annul "$BI" "new Date(nowMs + DEFAULT_EXPIRY_MS).toISOString()" "new Date(nowMs).toISOString()"
echo "== 6: sin aplanar el auth.json"; annul "$BI" "  return { ...record, ...(tokens as JsonRecord) }" "  return record"
echo "== 7: tokens anidados sin access token se aplanan"; annul "$BI" "  if (typeof (tokens as JsonRecord).access_token !== 'string') return record" "  void 0"
echo "== 8: camelCase pisa snake_case"; annul "$BI" "    if (out[snake] === undefined && typeof value === 'string' && value) out[snake] = value" "    if (typeof value === 'string' && value) out[snake] = value"
echo "== 9: sin la cuenta camelCase"; annul "$BI" "    fillFrom('account_id', (specific as JsonRecord).chatgptAccountId)" "    void 0"
echo "== 10: cualquier tipo"; annul "$BI" "  if (record.type !== undefined && record.type !== null && record.type !== 'codex') return" "  if (false) return"
echo "== 11: sin campos obligatorios"; annul "$BI" "    if (typeof record[field] !== 'string' || !record[field]) return" "    if (false) return"
echo "== 12: sin correo se importa"; annul "$BI" "  if (!email) return { ok: false" "  if (false) return { ok: false"
echo "== 13: el correo plano gana al del token"; annul "$BI" "const email = pickString(fromJwt.email, text(record.email))" "const email = pickString(text(record.email), fromJwt.email)"
echo "== 14: la cuenta no es el espacio de trabajo"; annul "$BI" "    providerSpecificData.workspaceId = chatgptAccountId" "    void 0"
echo "== 15: sin tokenExpiresAt"; annul "$BI" "    tokenExpiresAt: expiresAt," "    tokenExpiresAt: '',"
echo "== 16: una prioridad fraccionaria pasa"; annul "$BI" "Number.isInteger(record.priority) && record.priority > 0" "record.priority > 0"
echo "== 17: datos del proveedor vacíos se escriben"; annul "$BI" "  if (Object.keys(providerSpecificData).length > 0) payload.providerSpecificData = providerSpecificData" "  payload.providerSpecificData = providerSpecificData"
echo "== 18: la reimportación pisa lo guardado"; annul "$BI" "providerSpecificData: { ...toRecord(match.providerSpecificData), ...payload.providerSpecificData }" "providerSpecificData: payload.providerSpecificData"
echo "== 19: la reimportación conserva la prioridad"; annul "$BI" "  delete adjusted.priority" "  void 0"
echo "== 20: otra cuenta se toca"; annul "$BI" "connection.email === payload.email && " ""
echo "== 21: un texto es un registro"; annul "$BI" "  if (parsed && typeof parsed === 'object') return { ok: true, records: [parsed] }" "  if (parsed) return { ok: true, records: [parsed] }"
echo "== 22: un arreglo es una sesión"; annul "$SI" "  if (!trimmed.startsWith('{')) return false" "  if (!trimmed) return false"
echo "== 23: sin el nombre de sesión"; annul "$SI" " || nonEmpty(record.sessionToken) || nonEmpty(record.session_token)" ""
echo "== 24: sin tokens anidados"; annul "$SI" "  return nested ? nonEmpty(nested.access_token) || nonEmpty(nested.accessToken) : undefined" "  return undefined"
echo "== 25: cualquier token es un JWT"; annul "$SI" "  if (accessToken.split('.').length !== JWT_SEGMENTS) return" "  if (false) return"
echo "== 26: el expires no vence"; annul "$SI" "    if (Number.isFinite(ms) && ms <= nowMs) return true" "    void ms"
echo "== 27: el exp no vence"; annul "$SI" "  return typeof exp === 'number' && Number.isFinite(exp) && exp * MILLISECONDS_PER_SECOND <= nowMs" "  return false"
echo "== 28: sin el correo del usuario"; annul "$SI" "email: (user && nonEmpty(user.email)) || undefined" "email: undefined"
echo "== restaurado"; git -C "$T" status --short -- src/packages/provider/src/accounts/imports; run
