#!/usr/bin/env bash
# Anulaciones de #106e-5c-3: cookies web en el refresco proactivo.
set -u
T=${T:-/home/user/thyrox}; cd "$T/src/packages/provider"
P="src/accounts/webCookie/webCookieProviders.ts"
Z="src/accounts/webCookie/zaiToken.ts"
V="src/accounts/webCookie/webCookieProbe.ts"
H="src/accounts/refresh/health/webCookieHealthCheck.ts"
run() { timeout 120 bun test ./__tests__/accounts/webCookie ./__tests__/accounts/refresh/health/webCookieHealthCheck.test.ts 2>&1 | gawk '/^\(fail\)|^ *[0-9]+ (pass|fail)$/'; }
source "$T/.claude/workbench/mitm-f7h-api-20260928T070339/annul-lib.sh"
echo "== 1: heredados valen"; annul "$P" "return Object.hasOwn(WEB_COOKIE_PROBE_BASE_URLS, String(provider || '').toLowerCase())" "return String(provider || '').toLowerCase() in WEB_COOKIE_PROBE_BASE_URLS"
echo "== 2: sin minúsculas"; annul "$P" "String(provider || '').toLowerCase())" "String(provider || ''))"
echo "== 3: grok con /models"; annul "$P" "new Set(['huggingchat', 'grok-web'," "new Set(['huggingchat',"
echo "== 4: lmarena fiable"; annul "$P" "new Set(['lmarena'])" "new Set([])"
echo "== 5: JSON sin token"; annul "$Z" "const token = json.token ?? json.accessToken ?? json.access_token" "const token = json.token"
echo "== 6: token no textual"; annul "$Z" "return typeof token === 'string' ? token.trim() : ''" "return String(token ?? '').trim()"
echo "== 7: sin Bearer"; annul "$Z" "  if (bearer) return bearer[1]!.trim()" ""
echo "== 8: Bearer sensible a caja"; annul "$Z" "Bearer\s+(.+)\$/i)" "Bearer\s+(.+)\$/)"
echo "== 9: prefijo Cookie"; annul "$Z" "const cookie = withoutCookiePrefix(trimmed)" "const cookie = trimmed"
echo "== 10: sin token="; annul "$Z" "  if (match) return match[1]!.trim()" ""
echo "== 11: par suelto vale"; annul "$Z" "return cookie.includes(';') || cookie.includes('=') ? '' : cookie" "return cookie"
echo "== 12: JSON sin llave"; annul "$Z" "  if (!raw.startsWith('{')) return null" ""
echo "== 13: fuera de catálogo"; annul "$V" "  if (!Object.hasOwn(WEB_COOKIE_PROBE_BASE_URLS, provider)) return" "  if (false) return"
echo "== 14: sin cookie sondea"; annul "$V" "  if (!cookie) return { rejection" "  if (false) return { rejection"
echo "== 15: sin host sondea"; annul "$V" "  if (!registered || WEB_COOKIE_PROVIDERS_WITHOUT_AUTH_PROBE.has(provider)) return { rejection: UNSUPPORTED }" "  if (!registered) return { rejection: { valid: true, error: null, unsupported: false } }"
echo "== 16: wss o consulta sondea"; annul "$V" "  if (!/^https?:\/\//i.test(baseUrl) || baseUrl.includes('?')) return { rejection: UNSUPPORTED }" ""
echo "== 17: zai con cookie"; annul "$V" "  if (provider !== 'zai-web') return" "  if (true) return"
echo "== 18: zai sin token sondea"; annul "$V" "  if (!token) return { rejection: { valid: false, error: 'Z.ai web-session credential required', unsupported: false } }" ""
echo "== 19: cookie sin recortar"; annul "$V" "(apiKey || '').trim()" "(apiKey || '')"
echo "== 20: sigue redirecciones"; annul "$V" "redirect: 'manual'" "redirect: 'follow'"
echo "== 21: 403 vale"; annul "$V" "response.status === UNAUTHORIZED || response.status === FORBIDDEN" "response.status === UNAUTHORIZED"
echo "== 22: sin código AUTH_007"; annul "$V" "error: 'SESSION_EXPIRED', errorCode: 'AUTH_007', unsupported: false }" "error: 'SESSION_EXPIRED', unsupported: false }"
echo "== 23: redirección vale"; annul "$V" "    if (response.status >= FIRST_REDIRECT && response.status <= LAST_REDIRECT) {" "    if (false) {"
echo "== 24: sin API de modelos vale"; annul "$V" "    if (WEB_COOKIE_PROVIDERS_WITHOUT_MODELS_API.has(provider)) return UNSUPPORTED" ""
echo "== 25: red lanza"; annul "$V" "  } catch (error) {" "  } catch (error) { throw error;"
echo "== 26: error sin sanear"; annul "$V" "(message ? sanitizeErrorMessage(message) : '')" "(message ? String(message) : '')"
echo "== 27: chatgpt sondea"; annul "$V" "  if (provider === 'chatgpt-web') {" "  if (false) {"
echo "== 28: chatgpt sin su validador"; annul "$V" "    return special ? special(request) : UNSUPPORTED" "    return UNSUPPORTED"
echo "== 29: fuera de catálogo sondea"; annul "$H" "    if (!isWebCookieProvider(connection.provider)) return" ""
echo "== 30: sin intervalo"; annul "$H" "    if (lastCheckMs > 0 && new Date(stamp).getTime() - lastCheckMs < intervalMin * MINUTE_MS) return" ""
echo "== 31: intervalo inclusivo"; annul "$H" "- lastCheckMs < intervalMin * MINUTE_MS) return" "- lastCheckMs <= intervalMin * MINUTE_MS) return"
echo "== 32: nunca comprobado se salta"; annul "$H" "    if (lastCheckMs > 0 && new Date" "    if (new Date"
echo "== 33: sin credencial sondea"; annul "$H" "    if (!credential) {
      await store.update(id, { lastHealthCheckAt: stamp })
      return
    }" ""
echo "== 34: sin cookie en datos"; annul "$H" "  return typeof cookie === 'string' ? cookie.trim() : ''" "  return ''"
echo "== 35: apiKey sin recortar"; annul "$H" "typeof connection.apiKey === 'string' ? connection.apiKey.trim() : ''" "typeof connection.apiKey === 'string' ? connection.apiKey : ''"
echo "== 36: no soportado caduca"; annul "$H" "    if (result.valid || result.unsupported) {" "    if (result.valid) {"
echo "== 37: sólo por código"; annul "$H" "result.errorCode === SESSION_EXPIRED_CODE || String(result.error || '').toUpperCase().includes('SESSION_EXPIRED')" "result.errorCode === SESSION_EXPIRED_CODE"
echo "== 38: sólo por texto"; annul "$H" "result.errorCode === SESSION_EXPIRED_CODE || String" "String"
echo "== 39: sin caducar"; annul "$H" "    if (isSessionExpired(result)) {" "    if (false) {"
echo "== 40: ambiguo sin aviso"; annul "$H" "    log?.warn?.(LOG_TAG, \`\${label(connection)} probe inconclusive (\${result.error}); will retry next interval\`)" ""
echo "== 41: ambiguo sin sello"; annul "$H" "will retry next interval\`)
    await store.update(id, { lastHealthCheckAt: stamp })" "will retry next interval\`)"
echo "== restaurado"; run
