/**
 * Puerto de `ccnmt: packages/config/env/managed-constants.ts`. No es uno de
 * los 15 del alcance — es la dependencia de hoja que `managedEnv.ts`
 * necesita: sin imports propios (sólo declara conjuntos de nombres de
 * variables de entorno), se porta en el sitio en vez de bloquearse.
 *
 * Variables de entorno que gobiernan el ruteo de inferencia: qué proveedor
 * usar, a qué endpoint llegar, y qué IDs de modelo enviar.
 *
 * Cuando `CLAUDE_CODE_PROVIDER_MANAGED_BY_HOST` es verdadero en el entorno de
 * arranque, éstas se descartan del entorno proveniente de settings para que
 * la config de ruteo del host no quede sobreescrita por un
 * `~/.claude/settings.json` de usuario — p. ej. una config de Bedrock para
 * el CLI de terminal que rompería un host que sólo soporta auth first-party.
 *
 * Nota de mantenimiento (`@[MODEL LAUNCH]` en la fuente): un modelo nuevo
 * normalmente no requiere cambios aquí — `VERTEX_REGION_CLAUDE_*` se
 * empareja por prefijo. Un proveedor nuevo o una variable de ruteo nueva
 * (endpoint, proyecto, región, auth) sí.
 */
const PROVIDER_MANAGED_ENV_VARS = new Set([
  // La bandera misma — settings no puede desactivarla una vez que el host la puso
  'CLAUDE_CODE_PROVIDER_MANAGED_BY_HOST',
  // Selección de proveedor
  'CLAUDE_CODE_USE_BEDROCK',
  'CLAUDE_CODE_USE_VERTEX',
  'CLAUDE_CODE_USE_FOUNDRY',
  'CLAUDE_CODE_USE_GEMINI',
  // Config de endpoint (base URLs, identificadores de proyecto/recurso)
  'ANTHROPIC_BASE_URL',
  'ANTHROPIC_BEDROCK_BASE_URL',
  'ANTHROPIC_VERTEX_BASE_URL',
  'ANTHROPIC_FOUNDRY_BASE_URL',
  'ANTHROPIC_FOUNDRY_RESOURCE',
  'ANTHROPIC_VERTEX_PROJECT_ID',
  'GEMINI_BASE_URL',
  // Ruteo por región (VERTEX_REGION_CLAUDE_* por-modelo, se maneja por prefijo abajo)
  'CLOUD_ML_REGION',
  // Auth
  'ANTHROPIC_API_KEY',
  'ANTHROPIC_AUTH_TOKEN',
  'CLAUDE_CODE_OAUTH_TOKEN',
  'AWS_BEARER_TOKEN_BEDROCK',
  'ANTHROPIC_FOUNDRY_API_KEY',
  'CLAUDE_CODE_SKIP_BEDROCK_AUTH',
  'CLAUDE_CODE_SKIP_VERTEX_AUTH',
  'CLAUDE_CODE_SKIP_FOUNDRY_AUTH',
  'GEMINI_API_KEY',
  // Defaults de modelo — a menudo con formatos de ID específicos del proveedor
  'ANTHROPIC_MODEL',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL_DESCRIPTION',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES',
  'ANTHROPIC_DEFAULT_OPUS_MODEL',
  'ANTHROPIC_DEFAULT_OPUS_MODEL_DESCRIPTION',
  'ANTHROPIC_DEFAULT_OPUS_MODEL_NAME',
  'ANTHROPIC_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES',
  'ANTHROPIC_DEFAULT_SONNET_MODEL',
  'ANTHROPIC_DEFAULT_SONNET_MODEL_DESCRIPTION',
  'ANTHROPIC_DEFAULT_SONNET_MODEL_NAME',
  'ANTHROPIC_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES',
  // Específicas de proveedor OpenAI
  'OPENAI_API_KEY',
  'OPENAI_BASE_URL',
  'OPENAI_MODEL',
  'OPENAI_DEFAULT_HAIKU_MODEL',
  'OPENAI_DEFAULT_HAIKU_MODEL_DESCRIPTION',
  'OPENAI_DEFAULT_HAIKU_MODEL_NAME',
  'OPENAI_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES',
  'OPENAI_DEFAULT_OPUS_MODEL',
  'OPENAI_DEFAULT_OPUS_MODEL_DESCRIPTION',
  'OPENAI_DEFAULT_OPUS_MODEL_NAME',
  'OPENAI_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES',
  'OPENAI_DEFAULT_SONNET_MODEL',
  'OPENAI_DEFAULT_SONNET_MODEL_DESCRIPTION',
  'OPENAI_DEFAULT_SONNET_MODEL_NAME',
  'OPENAI_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES',
  'OPENAI_SMALL_FAST_MODEL',
  'ANTHROPIC_SMALL_FAST_MODEL',
  'ANTHROPIC_SMALL_FAST_MODEL_AWS_REGION',
  'CLAUDE_CODE_SUBAGENT_MODEL',
  'GEMINI_MODEL',
  'GEMINI_SMALL_FAST_MODEL',
  // Específicas de proveedor Gemini — separadas de Anthropic/OpenAI
  'GEMINI_DEFAULT_HAIKU_MODEL',
  'GEMINI_DEFAULT_HAIKU_MODEL_DESCRIPTION',
  'GEMINI_DEFAULT_HAIKU_MODEL_NAME',
  'GEMINI_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES',
  'GEMINI_DEFAULT_OPUS_MODEL',
  'GEMINI_DEFAULT_OPUS_MODEL_DESCRIPTION',
  'GEMINI_DEFAULT_OPUS_MODEL_NAME',
  'GEMINI_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES',
  'GEMINI_DEFAULT_SONNET_MODEL',
  'GEMINI_DEFAULT_SONNET_MODEL_DESCRIPTION',
  'GEMINI_DEFAULT_SONNET_MODEL_NAME',
  'GEMINI_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES',
])

const PROVIDER_MANAGED_ENV_PREFIXES = [
  // Overrides de región Vertex por-modelo — crece con cada lanzamiento, así
  // que se empareja por prefijo para no tener que actualizarlo con cada uno.
  'VERTEX_REGION_CLAUDE_',
]

export function isProviderManagedEnvVar(key: string): boolean {
  const upper = key.toUpperCase()
  return (
    PROVIDER_MANAGED_ENV_VARS.has(upper) ||
    PROVIDER_MANAGED_ENV_PREFIXES.some(p => upper.startsWith(p))
  )
}

/** Settings peligrosos que pueden ejecutar shell arbitrario. */
export const DANGEROUS_SHELL_SETTINGS = [
  'apiKeyHelper',
  'awsAuthRefresh',
  'awsCredentialExport',
  'gcpAuthRefresh',
  'otelHeadersHelper',
  'statusLine',
] as const

/**
 * Variables de entorno seguras que pueden aplicarse antes del diálogo de
 * confianza. Son settings específicos de Claude Code que no representan
 * riesgo de seguridad.
 *
 * IMPORTANTE: ésta es la fuente de verdad de qué variables son seguras.
 * Cualquier variable NO listada aquí se considera peligrosa y dispara un
 * diálogo de seguridad si llega vía settings gestionados remotos.
 */
export const SAFE_ENV_VARS = new Set([
  'ANTHROPIC_CUSTOM_HEADERS',
  'ANTHROPIC_CUSTOM_MODEL_OPTION',
  'ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION',
  'ANTHROPIC_CUSTOM_MODEL_OPTION_NAME',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL_DESCRIPTION',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES',
  'ANTHROPIC_DEFAULT_OPUS_MODEL',
  'ANTHROPIC_DEFAULT_OPUS_MODEL_DESCRIPTION',
  'ANTHROPIC_DEFAULT_OPUS_MODEL_NAME',
  'ANTHROPIC_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES',
  'ANTHROPIC_DEFAULT_SONNET_MODEL',
  'ANTHROPIC_DEFAULT_SONNET_MODEL_DESCRIPTION',
  'ANTHROPIC_DEFAULT_SONNET_MODEL_NAME',
  'ANTHROPIC_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES',
  // Específicas de proveedor OpenAI
  'OPENAI_DEFAULT_HAIKU_MODEL',
  'OPENAI_DEFAULT_HAIKU_MODEL_DESCRIPTION',
  'OPENAI_DEFAULT_HAIKU_MODEL_NAME',
  'OPENAI_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES',
  'OPENAI_DEFAULT_OPUS_MODEL',
  'OPENAI_DEFAULT_OPUS_MODEL_DESCRIPTION',
  'OPENAI_DEFAULT_OPUS_MODEL_NAME',
  'OPENAI_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES',
  'OPENAI_DEFAULT_SONNET_MODEL',
  'OPENAI_DEFAULT_SONNET_MODEL_DESCRIPTION',
  'OPENAI_DEFAULT_SONNET_MODEL_NAME',
  'OPENAI_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES',
  'ANTHROPIC_FOUNDRY_API_KEY',
  'ANTHROPIC_MODEL',
  'ANTHROPIC_SMALL_FAST_MODEL_AWS_REGION',
  'ANTHROPIC_SMALL_FAST_MODEL',
  'AWS_DEFAULT_REGION',
  'AWS_PROFILE',
  'AWS_REGION',
  'BASH_DEFAULT_TIMEOUT_MS',
  'BASH_MAX_OUTPUT_LENGTH',
  'BASH_MAX_TIMEOUT_MS',
  'CLAUDE_BASH_MAINTAIN_PROJECT_WORKING_DIR',
  'CLAUDE_CODE_API_KEY_HELPER_TTL_MS',
  'CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS',
  'CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC',
  'CLAUDE_CODE_DISABLE_TERMINAL_TITLE',
  'CLAUDE_CODE_ENABLE_TELEMETRY',
  'CLAUDE_CODE_IDE_SKIP_AUTO_INSTALL',
  'CLAUDE_CODE_MAX_OUTPUT_TOKENS',
  'CLAUDE_CODE_SKIP_BEDROCK_AUTH',
  'CLAUDE_CODE_SKIP_FOUNDRY_AUTH',
  'CLAUDE_CODE_SKIP_VERTEX_AUTH',
  'CLAUDE_CODE_SUBAGENT_MODEL',
  'CLAUDE_CODE_USE_BEDROCK',
  'CLAUDE_CODE_USE_FOUNDRY',
  'CLAUDE_CODE_USE_GEMINI',
  'CLAUDE_CODE_USE_VERTEX',
  'GEMINI_MODEL',
  'GEMINI_SMALL_FAST_MODEL',
  'GEMINI_DEFAULT_HAIKU_MODEL',
  'GEMINI_DEFAULT_HAIKU_MODEL_DESCRIPTION',
  'GEMINI_DEFAULT_HAIKU_MODEL_NAME',
  'GEMINI_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES',
  'GEMINI_DEFAULT_OPUS_MODEL',
  'GEMINI_DEFAULT_OPUS_MODEL_DESCRIPTION',
  'GEMINI_DEFAULT_OPUS_MODEL_NAME',
  'GEMINI_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES',
  'GEMINI_DEFAULT_SONNET_MODEL',
  'GEMINI_DEFAULT_SONNET_MODEL_DESCRIPTION',
  'GEMINI_DEFAULT_SONNET_MODEL_NAME',
  'GEMINI_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES',
  'DISABLE_AUTOUPDATER',
  'DISABLE_BUG_COMMAND',
  'DISABLE_COST_WARNINGS',
  'DISABLE_ERROR_REPORTING',
  'DISABLE_FEEDBACK_COMMAND',
  'DISABLE_TELEMETRY',
  'ENABLE_TOOL_SEARCH',
  'MAX_MCP_OUTPUT_TOKENS',
  'MAX_THINKING_TOKENS',
  'MCP_TIMEOUT',
  'MCP_TOOL_TIMEOUT',
  'OTEL_EXPORTER_OTLP_HEADERS',
  'OTEL_EXPORTER_OTLP_LOGS_HEADERS',
  'OTEL_EXPORTER_OTLP_LOGS_PROTOCOL',
  'OTEL_EXPORTER_OTLP_METRICS_CLIENT_CERTIFICATE',
  'OTEL_EXPORTER_OTLP_METRICS_CLIENT_KEY',
  'OTEL_EXPORTER_OTLP_METRICS_HEADERS',
  'OTEL_EXPORTER_OTLP_METRICS_PROTOCOL',
  'OTEL_EXPORTER_OTLP_PROTOCOL',
  'OTEL_EXPORTER_OTLP_TRACES_HEADERS',
  'OTEL_LOG_TOOL_DETAILS',
  'OTEL_LOG_USER_PROMPTS',
  'OTEL_LOGS_EXPORT_INTERVAL',
  'OTEL_LOGS_EXPORTER',
  'OTEL_METRIC_EXPORT_INTERVAL',
  'OTEL_METRICS_EXPORTER',
  'OTEL_METRICS_INCLUDE_ACCOUNT_UUID',
  'OTEL_METRICS_INCLUDE_SESSION_ID',
  'OTEL_METRICS_INCLUDE_VERSION',
  'OTEL_RESOURCE_ATTRIBUTES',
  'USE_BUILTIN_RIPGREP',
  'VERTEX_REGION_CLAUDE_3_5_HAIKU',
  'VERTEX_REGION_CLAUDE_3_5_SONNET',
  'VERTEX_REGION_CLAUDE_3_7_SONNET',
  'VERTEX_REGION_CLAUDE_4_0_OPUS',
  'VERTEX_REGION_CLAUDE_4_0_SONNET',
  'VERTEX_REGION_CLAUDE_4_1_OPUS',
  'VERTEX_REGION_CLAUDE_4_5_SONNET',
  'VERTEX_REGION_CLAUDE_4_6_SONNET',
  'VERTEX_REGION_CLAUDE_HAIKU_4_5',
])
