#!/usr/bin/env python3
"""Tabla de traduccion palabra a palabra, es -> en.

El criterio es el de `redaccion-tecnica-es.md`: **se traduce la palabra, no se
le busca un sinonimo mejor**. `modelo -> model`, no `model -> entity`. Una
palabra que ya esta en ingles no entra en la tabla.

La tabla es el UNICO juicio de este barrido; el resto es mecanico. Por eso vive
aparte del aplicador: se puede leer, revisar y volver a correr sin tocar el
recorrido de tokens.
"""

#: es -> en, por palabra suelta. El aplicador parte el identificador por `_`
#: y traduce cada pieza; lo que no este aqui se deja como esta.
LEXICON = {
    # --- traducir-identificadores-nuevos (2026-09-24) ---------------------
    'ahora': 'now',
    'anidado': 'nested',
    'ano': 'plain',
    'anota': 'notes',
    'anotadas': 'annotated',
    'apaga': 'disables',
    'apagado': 'disabled',
    'apagan': 'disable',
    'arquitectura': 'architecture',
    'asentadas': 'settled',
    'ausencia': 'absence',
    'ausentes': 'absent',
    'avisa': 'warns',
    'binario': 'binary',
    'cae': 'falls',
    'candidata': 'candidate',
    'candidatas': 'candidates',
    'cargar': 'load',
    'chico': 'small',
    'cifra': 'figure',
    'clausula': 'clause',
    'clave': 'key',
    'clon': 'clone',
    'coinciden': 'agree',
    'comodin': 'wildcard',
    'comparables': 'comparable',
    'compone': 'composes',
    'comprimida': 'compressed',
    'compuesto': 'composite',
    'condiciones': 'conditions',
    'conducta': 'behavior',
    'congelado': 'frozen',
    'consumidores': 'consumers',
    'contenedor': 'container',
    'contra': 'against',
    'corrida': 'run',
    'cota': 'bound',
    'credito': 'credit',
    'cuarto': 'fourth',
    'culpables': 'culprits',
    'deciden': 'decide',
    'decir': 'say',
    'declara': 'declares',
    'declaracion': 'declaration',
    'declarada': 'declared',
    'dentro': 'inside',
    'dependencia': 'dependency',
    'derrame': 'spill',
    'desconocidas': 'unknown',
    'desempate': 'tie_break',
    'destinos': 'targets',
    'desvia': 'diverts',
    'detalle': 'detail',
    'digitaliza': 'digitizes',
    'directorios': 'directories',
    'disparando': 'firing',
    'disparar': 'fire',
    'disparo': 'firing',
    'duenos': 'owners',
    'emitidas': 'emitted',
    'empeoran': 'worsen',
    'encendido': 'enabled',
    'encienden': 'enable',
    'enlace': 'link',
    'entera': 'whole',
    'escribir': 'write',
    'escritura': 'write',
    'existe': 'exists',
    'existente': 'existing',
    'falso': 'false',
    'filtra': 'filters',
    'fuente': 'source',
    'fuentes': 'sources',
    'fugas': 'leaks',
    'gana': 'wins',
    'grande': 'large',
    'guarda': 'guard',
    'hallados': 'found',
    'hereda': 'inherits',
    'hermana': 'sibling',
    'hermano': 'sibling',
    'hogar': 'home',
    'imagen': 'image',
    'indicios': 'hints',
    'instrumento': 'instrument',
    'lengua': 'language',
    'listado': 'listing',
    'llamada': 'call',
    'mandando': 'ruling',
    'medidos': 'measured',
    'medio': 'middle',
    'mencion': 'mention',
    'ningun': 'no',
    'nuevo': 'new',
    'ocupadas': 'occupied',
    'parametros': 'parameters',
    'pares': 'pairs',
    'partida': 'start',
    'partir': 'split',
    'positivo': 'positive',
    'posterior': 'later',
    'prefijo': 'prefix',
    'primer': 'first',
    'propio': 'own',
    'propios': 'own',
    'puede': 'can',
    'punto': 'point',
    'rama': 'branch',
    'recolectar': 'collect',
    'repuntado': 'repointed',
    'respaldo': 'fallback',
    'responde': 'answers',
    'resuelve': 'resolves',
    'sea': 'be',
    'sobrantes': 'leftovers',
    'suelto': 'loose',
    'sufijo': 'suffix',
    'techo': 'ceiling',
    'tener': 'have',
    'tercer': 'third',
    'unica': 'only',
    'varios': 'several',
    'viejo': 'old',
    # --- sustantivos de estructura -------------------------------------
    'alcance': 'scope', 'ancho': 'width', 'ancla': 'anchor', 'arbol': 'tree',
    'archivo': 'file', 'archivos': 'files', 'artefacto': 'artifact',
    'aviso': 'warning', 'biblioteca': 'library', 'libreria': 'library',
    'bloque': 'block', 'cabecera': 'header', 'campos': 'fields', 'capa': 'layer',
    'carpeta': 'folder', 'caso': 'case', 'casos': 'cases', 'cita': 'citation',
    'citas': 'citations', 'clases': 'classes', 'codigo': 'code',
    'columnas': 'columns', 'comando': 'command', 'comandos': 'commands',
    'constructos': 'constructs', 'consumidor': 'consumer', 'contenido': 'content',
    'conteo': 'count', 'copia': 'copy', 'correccion': 'fix', 'corte': 'cut',
    'cubos': 'buckets', 'cuenta': 'count', 'cuerpo': 'body',
    'defecto': 'defect', 'definiciones': 'definitions',
    'descripcion': 'description', 'destino': 'target', 'diferencias': 'diffs',
    'directivas': 'directives', 'directorio': 'directory', 'dominio': 'domain',
    'ejecutable': 'executable', 'ejes': 'axes', 'encabezados': 'headings',
    'entorno': 'environment', 'entrada': 'entry', 'envoltorio': 'wrapper',
    'escalon': 'tier', 'escenario': 'scenario', 'etiqueta': 'label',
    'evento': 'event', 'eventos': 'events', 'evidencia': 'evidence',
    'extensiones': 'extensions', 'falla': 'failure', 'fallos': 'failures',
    'familia': 'family', 'fila': 'row', 'filas': 'rows', 'fin': 'end',
    'forma': 'form', 'formas': 'forms', 'gemelo': 'twin', 'gestion': 'management',
    'grafias': 'spellings', 'grupo': 'group', 'guion': 'script',
    'hallazgo': 'finding', 'hallazgos': 'findings', 'indice': 'index',
    'informe': 'report', 'inicio': 'start', 'interpretes': 'interpreters',
    'lectura': 'read', 'lexico': 'lexicon', 'linea': 'line', 'lineas': 'lines',
    'literales': 'literals', 'longitud': 'length', 'lugar': 'place',
    'manija': 'handle', 'marca': 'mark', 'marcas': 'marks',
    'marcador': 'marker', 'marco': 'frame', 'mediana': 'median',
    'memoria': 'memory', 'mensaje': 'message', 'mitad': 'half',
    'modelo': 'model', 'modelos': 'models', 'momento': 'moment',
    'muestra': 'sample', 'nivel': 'level', 'nodo': 'node', 'nodos': 'nodes',
    'nombre': 'name', 'nombres': 'names', 'nota': 'note', 'numero': 'number',
    'numeros': 'numbers', 'objetivo': 'target', 'objetivos': 'targets',
    'ordinales': 'ordinals', 'origen': 'source', 'pagina': 'page',
    'paginas': 'pages', 'paquete': 'package', 'parseo': 'parse',
    'partes': 'parts', 'paseo': 'walk', 'pesos': 'weights', 'pieza': 'piece',
    'piezas': 'pieces', 'plantilla': 'template', 'plantillas': 'templates',
    'poblacion': 'population', 'poda': 'prune', 'posicion': 'position',
    'precios': 'prices', 'precondicion': 'precondition', 'prefijos': 'prefixes',
    'proceso': 'process', 'produccion': 'production', 'prosa': 'prose',
    'proveedor': 'provider', 'puentes': 'bridges', 'raiz': 'root',
    'rampa': 'ramp', 'rango': 'range', 'razon': 'reason',
    'referencia': 'reference', 'registro': 'record', 'registros': 'records',
    'remuestreo': 'resampling', 'reparto': 'split', 'reporte': 'report',
    'resultado': 'result', 'resultados': 'results', 'ruido': 'noise',
    'ruta': 'path', 'salida': 'output', 'seccion': 'section',
    'secciones': 'sections', 'segmento': 'segment', 'semilla': 'seed',
    'sesion': 'session', 'sesiones': 'sessions', 'simbolo': 'symbol',
    'sitios': 'sites', 'sonda': 'probe', 'subrayado': 'underscore',
    'sujeto': 'subject', 'suma': 'sum', 'sustituciones': 'substitutions',
    'tabla': 'table', 'tareas': 'tasks', 'tarjeta': 'card',
    'terminos': 'terms', 'texto': 'text', 'titulo': 'title',
    'titulos': 'titles', 'tope': 'cap', 'ubicacion': 'location',
    'umbral': 'threshold', 'valor': 'value', 'valores': 'values',
    'variantes': 'variants', 'varianza': 'variance', 'covarianza': 'covariance',
    'vecino': 'neighbor', 'veredicto': 'verdict', 'veredictos': 'verdicts',
    'vistas': 'views', 'capacidades': 'capabilities', 'candidato': 'candidate',
    'candidatos': 'candidates', 'apertura': 'opening', 'caida': 'drop',
    'caidas': 'drops', 'resid': 'residual', 'desv': 'std',
    # --- adjetivos y participios ---------------------------------------
    'absoluta': 'absolute', 'ajena': 'foreign', 'alcanzado': 'reached',
    'alta': 'high', 'alterna': 'alternate', 'alto': 'high',
    'anulado': 'nulled', 'anterior': 'previous', 'aplicado': 'applied',
    'apretada': 'tight', 'aprobados': 'approved', 'ausente': 'missing',
    'baja': 'low', 'bajo': 'low', 'balanceado': 'balanced', 'blanco': 'blank',
    'caidos': 'dropped', 'ciego': 'blind', 'completa': 'complete',
    'completo': 'complete', 'compuestos': 'composite', 'corregidos': 'fixed',
    'correlacionada': 'correlated', 'corta': 'short', 'cruda': 'raw',
    'crudo': 'raw', 'cubiertos': 'covered', 'debil': 'weak',
    'debiles': 'weak', 'declaradas': 'declared', 'declarado': 'declared',
    'declarados': 'declared', 'destilado': 'distilled', 'divergentes': 'divergent',
    'dominante': 'dominant', 'efimeras': 'ephemeral', 'elegido': 'chosen',
    'encontradas': 'found', 'encontrados': 'found', 'equivalentes': 'equivalent',
    'escritas': 'written', 'espanoles': 'spanish', 'esperado': 'expected',
    'esperados': 'expected', 'exigido': 'required', 'exigidos': 'required',
    'extraido': 'extracted', 'falsas': 'false', 'faltantes': 'missing',
    'guardadas': 'saved', 'hallada': 'found', 'hallado': 'found',
    'hecho': 'done', 'holgado': 'loose', 'huerfana': 'orphan',
    'huerfanas': 'orphans', 'huerfano': 'orphan', 'huerfanos': 'orphans',
    'humedo': 'wet', 'igual': 'equal', 'independiente': 'independent',
    'intacta': 'intact', 'intactos': 'intact', 'inyectado': 'injected',
    'leido': 'read', 'libre': 'free', 'limpio': 'clean', 'lineal': 'linear',
    'llano': 'plain', 'marcado': 'marked', 'marcados': 'marked',
    'mayor': 'max', 'medido': 'measured', 'menos': 'minus', 'mismo': 'same',
    'nueva': 'new', 'nulo': 'null', 'opcional': 'optional',
    'ordenadas': 'sorted', 'ordenados': 'sorted', 'otra': 'other',
    'otro': 'other', 'parcial': 'partial', 'pendientes': 'pending',
    'plana': 'flat', 'plano': 'flat', 'presentes': 'present',
    'previa': 'previous', 'previo': 'previous', 'primero': 'first',
    'propia': 'own', 'propias': 'own', 'punteado': 'dotted',
    'raro': 'odd', 'reales': 'real', 'reclamados': 'claimed',
    'reconciliado': 'reconciled', 'recta': 'line', 'relativa': 'relative',
    'relativo': 'relative', 'requerido': 'required', 'requeridos': 'required',
    'rota': 'broken', 'ruidosa': 'noisy', 'ruidosos': 'noisy',
    'seco': 'dry', 'siguiente': 'next', 'sintetico': 'synthetic',
    'sostenido': 'sustained', 'subnormal': 'subnormal', 'tercera': 'third',
    'torcida': 'skewed', 'truncado': 'truncated', 'ultimo': 'last',
    'unida': 'joined', 'uniforme': 'uniform', 'vacio': 'empty',
    'vetadas': 'banned', 'vieja': 'old', 'vistos': 'seen', 'vivas': 'live',
    'vivo': 'live', 'giro': 'spin', 'alfa': 'alpha',
    # --- verbos ---------------------------------------------------------
    'acunar': 'mint', 'bajar': 'lower', 'cabe': 'fits', 'cierre': 'close',
    'corregir': 'fix', 'cortar': 'cut', 'correr': 'run', 'devuelto': 'returned',
    'discrimina': 'discriminates', 'dispara': 'fires', 'existen': 'exist',
    'faltan': 'missing', 'hay': 'has', 'limpiar': 'clean', 'llega': 'arrives',
    'llenado': 'filled', 'medir': 'measure', 'midio': 'measured',
    'pasa': 'passes', 'preserva': 'preserves', 'publica': 'publishes',
    'reconcilia': 'reconciles', 'rehusa': 'refuses', 'rehuso': 'refused',
    'reporta': 'reports', 'reportandose': 'reported', 'resolver': 'resolve',
    'sigue': 'still', 'verificar': 'verify',
    # --- particulas y determinantes -------------------------------------
    'a': 'to', 'antes': 'before', 'aqui': 'here', 'con': 'with', 'de': 'of',
    'del': 'of', 'desde': 'from', 'despues': 'after', 'donde': 'where',
    'dos': 'two', 'el': 'the', 'en': 'in', 'esta': 'is', 'fuera': 'outside',
    'hasta': 'until', 'los': 'the', 'por': 'by', 'que': 'that', 'sin': 'without',
    'sus': 'its', 'todo': 'all', 'todos': 'all', 'tras': 'after', 'tres': 'three',
    'una': 'one', 'uno': 'one', 'cero': 'zero', 'cuantas': 'how_many',
    'cuando': 'when',
}

#: Conectivas que el LEXICO DEL GATE no marca —son demasiado cortas o existen
#: en los dos idiomas— pero que quedan dentro de un identificador que si se
#: toca. Sin ellas el resultado es mitad y mitad: `test_preserva_el_parseo`
#: acababa en `test_preserves_the_parse_y_es_idempotente`. No cambian el
#: veredicto del gate (nunca las marca); cambian la legibilidad del resultado.
LEXICON.update({
    'y': 'and', 'es': 'is', 'no': 'not', 'si': 'whether', 'la': 'the',
    'las': 'the', 'lo': 'the', 'al': 'to', 'un': 'a', 'como': 'like',
    'para': 'to', 'mas': 'more', 'ya': 'already', 'solo': 'only',
    'cada': 'each', 'tambien': 'also', 'ni': 'nor', 'pero': 'but',
    'entre': 'between', 'sobre': 'about', 'hacia': 'toward',
    'cuyo': 'whose', 'cuya': 'whose', 'este': 'this', 'ese': 'that',
    'esos': 'those', 'estos': 'these', 'estas': 'these', 'esas': 'those',
    'misma': 'same', 'mismos': 'same', 'mismas': 'same', 'otras': 'other',
    'otros': 'other', 'ambos': 'both', 'ambas': 'both', 'cuatro': 'four',
    'cinco': 'five', 'seis': 'six', 'siete': 'seven', 'ocho': 'eight',
    'nueve': 'nine', 'diez': 'ten', 'segundo': 'second', 'segunda': 'second',
    'primera': 'first', 'muchos': 'many', 'pocos': 'few', 'nada': 'nothing',
    'algo': 'something', 'nunca': 'never', 'siempre': 'always',
})
