/**
 * WaitForMcpServers tool — port of ant v2.1.132 Iz8 (3105.js UK7).
 *
 * Behaviour mirrors ant byte-for-byte:
 *   - input.servers (optional) — when present, restrict the wait to those
 *     names; when absent, wait for every currently-pending server.
 *   - poll the MCP client list every 50ms until either:
 *       * no requested server is still in `pending`, OR
 *       * G55 = 5000ms elapses, OR
 *       * the abort signal fires.
 *   - normalise server names via `F1(name)` (lowercase + non-alnum strip
 *     into underscore) so the caller can say "GitHub" and we still match
 *     a server named "github_remote".
 *   - emit `tengu_mcp_pending_call` with full counts + waitMs + matched.
 *
 * Tool registration:
 *   - isReadOnly: true
 *   - isConcurrencySafe: false  (ant 3105: a wait blocks the agent loop,
 *     parallel waits would just serialise behind the same poll)
 *   - checkPermissions: always allow (no user prompt)
 *   - isEnabled: Cz8 — tengu_ashen_kelp flag AND at least one pending server
 */
import { z } from 'zod/v4'
import {
  type AnalyticsMetadata_I_VERIFIED_THIS_IS_NOT_CODE_OR_FILEPATHS,
  logEvent,
} from '@claude-code-how-works/local-observability'
import { getFeatureValue_CACHED_MAY_BE_STALE } from '@claude-code-how-works/config/feature-flags'
import { logForDebugging } from '@claude-code-how-works/local-observability/debug.js'
import { sleep } from '@claude-code-how-works/config/sleep'
import { getMainLoopModel } from '@claude-code-how-works/provider/model.js'
import { getMcpClientsFromAccessor } from '@claude-code-how-works/app-host/bootstrap/state.js'
import { buildTool, type ToolDef } from '../../Tool.js'
import { lazySchema } from '../../utils/lazySchema.js'
import {
  WAIT_FOR_MCP_SERVERS_MAX_BLOCK_MS,
  WAIT_FOR_MCP_SERVERS_POLL_MS,
  WAIT_FOR_MCP_SERVERS_TOOL_NAME,
} from './constants.js'
import { getWaitForMcpServersPrompt } from './prompt.js'

/**
 * Normalise server names for matching. Byte-for-byte port of ant `l1`
 * (0676.js):
 *
 *   function l1(H){
 *     let _ = H.replace(/[^a-zA-Z0-9_-]/g, "_");
 *     if (H.startsWith("claude.ai "))
 *       _ = _.replace(/_+/g, "_").replace(/^_|_$/g, "");
 *     return _
 *   }
 *
 * Critical differences from a naive lowercase-and-strip implementation:
 *   1. Case is PRESERVED — ant does NOT call `.toLowerCase()`. A
 *      "GitHub" server stays "GitHub" after normalisation; matching
 *      against a server registered as "github_remote" only fires when
 *      the user types "github_remote" (or close to it), NOT just
 *      "GitHub". This is a server-identifier normalisation, not a
 *      fuzzy-name matcher.
 *   2. Character class KEEPS `_` and `-` — they're identifier-safe
 *      characters in MCP server names. Only outside-alphanumeric chars
 *      (spaces, dots, slashes, etc.) collapse to `_`.
 *   3. Each unsafe character becomes ONE underscore — `/g` replace
 *      per-char, NOT `[…]+` greedy. "foo  bar" → "foo__bar", NOT
 *      "foo_bar". The collapse-runs step (`_+` → `_`) is reserved for
 *      the `"claude.ai "` prefix case below.
 *   4. ONLY names that originally started with `"claude.ai "` get the
 *      run-collapse + leading/trailing strip — because those names are
 *      generated by the bridge layer and tend to be "claude.ai
 *      Generated  Server  Name" with multi-space runs that would
 *      otherwise yield "claude_ai_Generated__Server__Name__".
 */
export function normalizeServerName(name: string): string {
  let normalized = name.replace(/[^a-zA-Z0-9_-]/g, '_')
  if (name.startsWith('claude.ai ')) {
    normalized = normalized.replace(/_+/g, '_').replace(/^_|_$/g, '')
  }
  return normalized
}

/**
 * Models that do NOT support tool_reference blocks. Mirrors ant `Bt5`
 * (4025.js); also read from `tengu_tool_search_unsupported_models` JSON
 * config when present. Tool-reference support is required for tool-search
 * mode where MCP tools are deferred; on older models the agent can't
 * defer-and-discover, so WaitForMcpServers becomes the only way to
 * block until MCP tools are ready.
 */
const TOOL_REFERENCE_UNSUPPORTED_FALLBACK = ['haiku']

function getToolReferenceUnsupportedModels(): readonly string[] {
  try {
    // ant Ut5(): the override is published as `tengu_tool_search_unsupported_models`
    // and returns either a string[] or null. The narrowing helper accepts a
    // typed fallback (unknown[]) so we don't need a `null as unknown` cast.
    const flag = getFeatureValue_CACHED_MAY_BE_STALE<unknown[]>(
      'tengu_tool_search_unsupported_models',
      [],
    )
    if (Array.isArray(flag) && flag.length > 0) {
      return flag.filter((v): v is string => typeof v === 'string')
    }
  } catch {
    // flag access failed — fall through to the static fallback
  }
  return TOOL_REFERENCE_UNSUPPORTED_FALLBACK
}

/**
 * Ant `DRH(model)`. Returns true when the model supports tool_reference
 * blocks (= it can defer MCP tools). The unsupported list is a substring
 * match against the lowercased model id.
 */
function modelSupportsToolReference(model: string): boolean {
  const lower = model.toLowerCase()
  for (const needle of getToolReferenceUnsupportedModels()) {
    if (lower.includes(needle.toLowerCase())) return false
  }
  return true
}

/**
 * Snapshot the current main-loop model — wrapped in try/catch so the
 * isEnabled gate doesn't crash when bindings aren't installed yet
 * (e.g. tool registry warm-up before app-host bootstrap).
 */
function getMainLoopModelForGate(): string {
  try {
    return getMainLoopModel()
  } catch {
    return ''
  }
}

/** Ant `F37`. Pending server names from the live MCP client list. */
function getPendingMcpServerNames(): string[] {
  try {
    const clients = getMcpClientsFromAccessor() ?? []
    return clients.filter(c => c.type === 'pending').map(c => c.name)
  } catch {
    return []
  }
}

/** Ant `F37().length > 0`. */
function hasPendingMcpServer(): boolean {
  return getPendingMcpServerNames().length > 0
}

const inputSchema = lazySchema(() =>
  z.object({
    servers: z
      .array(z.string())
      .optional()
      .describe('Server names to wait for (default: all pending)'),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.object({
    ready: z.boolean(),
    connected: z.array(z.string()),
    failed: z.array(z.string()),
    stillPending: z.array(z.string()),
    needsAuth: z.array(z.string()),
    disabled: z.array(z.string()),
    unknown: z.array(z.string()),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>

export type Output = z.infer<OutputSchema>

export const WaitForMcpServersTool = buildTool({
  name: WAIT_FOR_MCP_SERVERS_TOOL_NAME,
  searchHint: 'wait for MCP servers that are still connecting',
  maxResultSizeChars: 10_000,
  isReadOnly() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isEnabled() {
    // Port of ant v2.1.136 ew8 (3146.js):
    //   1. `tengu_ashen_kelp` feature flag must be on.
    //   2. Current model must NOT support tool_reference blocks — when
    //      the model can defer MCP tools via tool-search, the agent can
    //      reach for them directly without an explicit wait. ant Bt5
    //      lists models without tool_reference support (currently
    //      ["haiku"]); modelSupportsToolReference returns true when the
    //      model is supported, false otherwise.
    //   3. There must be at least one currently-pending MCP server —
    //      otherwise the wait would return immediately and the tool is
    //      noise in the prompt.
    if (!getFeatureValue_CACHED_MAY_BE_STALE('tengu_ashen_kelp', false)) {
      return false
    }
    if (modelSupportsToolReference(getMainLoopModelForGate())) {
      return false
    }
    return hasPendingMcpServer()
  },
  async description() {
    return getWaitForMcpServersPrompt()
  },
  async prompt() {
    return getWaitForMcpServersPrompt()
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  toAutoClassifierInput(input) {
    return (input.servers ?? []).join(', ')
  },
  userFacingName() {
    return 'MCP Wait For Servers'
  },
  async checkPermissions(input) {
    return { behavior: 'allow' as const, updatedInput: input }
  },
  async call(input, context) {
    const { abortController } = context
    // Ant `A = () => q?.() ?? T?.().clients ?? K` — re-reads on every
    // poll iteration. The original ccb impl froze the snapshot at
    // entry, which made the poll loop USELESS: it would spin until the
    // 5s deadline because the snapshot never picked up new client
    // states. Fix: read live from the app-host state accessor on every
    // poll (which is what `getMcpClientsFromAccessor` returns), and
    // fall back to `context.options.mcpClients` only when the accessor
    // is unbound (test fixtures).
    const liveClients = (): readonly { name: string; type: string }[] => {
      try {
        const fromState = getMcpClientsFromAccessor()
        if (fromState && fromState.length > 0) return fromState
      } catch {
        // accessor not wired (e.g. unit tests) — fall through
      }
      return context.options.mcpClients ?? []
    }

    // Snapshot the requested server list. Empty → "all currently pending".
    const initialSnapshot = liveClients()
    const requested =
      input.servers && input.servers.length > 0
        ? input.servers
        : initialSnapshot.filter(c => c.type === 'pending').map(c => c.name)
    const normalizedRequested = new Set(requested.map(normalizeServerName))

    const matching = (): readonly { name: string; type: string }[] =>
      liveClients().filter(
        c =>
          requested.includes(c.name) ||
          normalizedRequested.has(normalizeServerName(c.name)),
      )

    const start = Date.now()
    const deadline = start + WAIT_FOR_MCP_SERVERS_MAX_BLOCK_MS

    // Poll loop (ant inline while-loop). 50ms is short enough to feel
    // responsive but cheap enough that 5s of polling burns <100 wakeups.
    while (
      matching().some(c => c.type === 'pending') &&
      Date.now() < deadline &&
      !abortController.signal.aborted
    ) {
      await sleep(WAIT_FOR_MCP_SERVERS_POLL_MS, abortController.signal)
    }

    const waitedMs = Date.now() - start
    const snapshot = matching()
    const connected: string[] = []
    const failed: string[] = []
    const stillPending: string[] = []
    const needsAuth: string[] = []
    const disabled: string[] = []
    for (const client of snapshot) {
      switch (client.type) {
        case 'connected':
          connected.push(client.name)
          break
        case 'failed':
          failed.push(client.name)
          break
        case 'pending':
          stillPending.push(client.name)
          break
        case 'needs-auth':
          needsAuth.push(client.name)
          break
        case 'disabled':
          disabled.push(client.name)
          break
        default:
          break
      }
    }
    const seen = new Set(snapshot.map(c => normalizeServerName(c.name)))
    const unknown = requested.filter(r => !seen.has(normalizeServerName(r)))
    const ready =
      stillPending.length === 0 &&
      failed.length === 0 &&
      needsAuth.length === 0 &&
      disabled.length === 0 &&
      unknown.length === 0

    logForDebugging(
      `[WaitForMcpServers] waited=${waitedMs}ms connected=${connected.join(',')} failed=${failed.join(',')} pending=${stillPending.join(',')} needsAuth=${needsAuth.join(',')} disabled=${disabled.join(',')} unknown=${unknown.join(',')}`,
    )
    logEvent('tengu_mcp_pending_call', {
      requestedCount: requested.length,
      connectedCount: connected.length,
      failedCount: failed.length,
      pendingCount: stillPending.length,
      needsAuthCount: needsAuth.length,
      disabledCount: disabled.length,
      unknownCount: unknown.length,
      waitMs: waitedMs,
      matched: ready,
      matchType:
        'wait' as AnalyticsMetadata_I_VERIFIED_THIS_IS_NOT_CODE_OR_FILEPATHS,
      success: ready,
    })

    return {
      data: {
        ready,
        connected,
        failed,
        stillPending,
        needsAuth,
        disabled,
        unknown,
      },
    }
  },
  renderToolUseMessage(input) {
    const names = input.servers?.join(', ')
    return names
      ? `Wait for MCP servers to connect: ${names}`
      : 'Wait for pending MCP servers to connect'
  },
  renderToolResultMessage() {
    return null
  },
  renderToolUseProgressMessage() {
    return null
  },
  renderToolUseErrorMessage() {
    return null
  },
  renderToolUseRejectedMessage() {
    return null
  },
  mapToolResultToToolResultBlockParam(output, toolUseID) {
    const lines = [
      `ready: ${output.ready}`,
      output.connected.length > 0
        ? `Connected (their tools are now available — call them directly): ${output.connected.join(', ')}`
        : '',
      output.failed.length > 0
        ? `Failed to connect: ${output.failed.join(', ')}`
        : '',
      output.stillPending.length > 0
        ? `Still connecting (try again or proceed without): ${output.stillPending.join(', ')}`
        : '',
      output.needsAuth.length > 0
        ? `Needs authentication (ask the user to run /mcp): ${output.needsAuth.join(', ')}`
        : '',
      output.disabled.length > 0
        ? `Disabled (ask the user to enable via /mcp): ${output.disabled.join(', ')}`
        : '',
      output.unknown.length > 0
        ? `Unknown (no MCP server with this name is configured): ${output.unknown.join(', ')}`
        : '',
    ].filter(Boolean)
    return {
      type: 'tool_result' as const,
      tool_use_id: toolUseID,
      content: lines.join('\n'),
      is_error: !output.ready,
    }
  },
} satisfies ToolDef<InputSchema, Output>)
