#!/usr/bin/env bash
# Anulaciones de #106e-5b-1: decisión del refresco proactivo por conexión.
set -u
T=${T:-/home/user/thyrox}; cd "$T/src/packages/provider"
P="src/accounts/refresh/health/checkPlan.ts"
run() { timeout 120 bun test ./__tests__/accounts/refresh/health/checkPlan.test.ts 2>&1 | gawk '/^\(fail\)|^ *[0-9]+ (pass|fail)$/'; }
source "$T/.claude/workbench/mitm-f7h-api-20260928T070339/annul-lib.sh"
echo "== 1: sin id pasa"; annul "$P" "  if (!connection?.id) return SKIP" ""
echo "== 2: sin exclusión por proveedor"; annul "$P" "  if (context.skipProviders.has(provider)) return SKIP" ""
echo "== 3: intervalo cero comprueba"; annul "$P" "  if (intervalMin <= 0) return SKIP" ""
echo "== 4: inactiva expirada no se reintenta"; annul "$P" "  if (!connection.isActive && !(connection.testStatus === 'expired' && expiredRetryCount(connection) < EXPIRED_RETRY_MAX)) return SKIP" "  if (!connection.isActive) return SKIP"
echo "== 5: sin guarda terminal"; annul "$P" "  if (isTerminal(connection, provider)) return SKIP" ""
echo "== 6: baneada sin minúsculas"; annul "$P" "TERMINAL_STATUSES.has(connection.testStatus.toLowerCase())" "TERMINAL_STATUSES.has(connection.testStatus)"
echo "== 7: copilot expirada es terminal"; annul "$P" "  return !githubWithoutRefresh && !cursorAlive && !retryBudgetLeft" "  return !cursorAlive && !retryBudgetLeft"
echo "== 8: cursor expirada es terminal"; annul "$P" "  return !githubWithoutRefresh && !cursorAlive && !retryBudgetLeft" "  return !githubWithoutRefresh && !retryBudgetLeft"
echo "== 9: cuenta desactivada se reintenta"; annul "$P" "  const retryBudgetLeft = connection.lastErrorType !== 'account_deactivated' && " "  const retryBudgetLeft = "
echo "== 10: retirado no se marca"; annul "$P" "  if (deprecation) return { action: 'mark'" "  if (false) return { action: 'mark'"
echo "== 11: cursor siempre"; annul "$P" "    if (expiresAtMs > 0 && !aboutToExpire) return SKIP
    return isInRefreshBackoff" "    return isInRefreshBackoff"
echo "== 12: cursor ignora el circuito"; annul "$P" "    return isInRefreshBackoff(connection, context.nowMs) ? SKIP : { action: 'cursor' }" "    return { action: 'cursor' }"
echo "== 13: margen de 10 min"; annul "$P" "const TOKEN_EXPIRY_BUFFER_MS = 5 * MS_PER_MINUTE" "const TOKEN_EXPIRY_BUFFER_MS = 10 * MS_PER_MINUTE"
echo "== 14: sin kimi_web"; annul "$P" "new Set(['kimi-web', 'kimi_web'])" "new Set(['kimi-web'])"
echo "== 15: kimi sin minúsculas"; annul "$P" "  const provider = lowerId(connection.provider)" "  const provider = String(connection.provider || '')"
echo "== 16: cookie sin intervalo"; annul "$P" "{ action: 'web-cookie', intervalMin }" "{ action: 'web-cookie', intervalMin: 60 }"
echo "== 17: refresh no texto vale"; annul "$P" "  if (!connection.refreshToken || typeof connection.refreshToken !== 'string') {" "  if (!connection.refreshToken) {"
echo "== 18: copilot pide reautenticar"; annul "$P" "    if (isGithubAccessTokenOnlyConnection(connection)) return { action: 'github-copilot' }" ""
echo "== 19: sin refresco no pide reautenticar"; annul "$P" "    const needsReauth = context.supportsTokenRefresh(String(connection.provider)) && " "    const needsReauth = "
echo "== 20: otro estado pide reautenticar"; annul "$P" " && (!connection.testStatus || connection.testStatus === 'active') && !connection.apiKey" " && !connection.apiKey"
echo "== 21: clave de API pide reautenticar"; annul "$P" " === 'active') && !connection.apiKey" " === 'active')"
echo "== 22: agotada no se desactiva"; annul "$P" "    if (retries >= EXPIRED_RETRY_MAX) return { action: 'deactivate' }" "    if (retries >= EXPIRED_RETRY_MAX) return SKIP"
echo "== 23: reintento sin espera"; annul "$P" "    if (context.nowMs - lastRetryMs < EXPIRED_RETRY_BACKOFF_MIN * MS_PER_MINUTE * 2 ** retries) return SKIP" ""
echo "== 24: espera sin doblar"; annul "$P" "EXPIRED_RETRY_BACKOFF_MIN * MS_PER_MINUTE * 2 ** retries" "EXPIRED_RETRY_BACKOFF_MIN * MS_PER_MINUTE"
echo "== 25: sin número de intento"; annul "$P" "    retryAttempt = retries + 1" ""
echo "== 26: sin ruta se refresca"; annul "$P" "  if (!context.supportsTokenRefresh(String(connection.provider))) return { action: 'touch' }" ""
echo "== 27: rota por calendario"; annul "$P" "expiresAtMs === 0 && !ROTATING_REFRESH_PROVIDERS.has(provider) &&" "expiresAtMs === 0 &&"
echo "== 28: calendario con caducidad conocida"; annul "$P" "const dueByInterval = expiresAtMs === 0 && " "const dueByInterval = "
echo "== 29: calendario de 30 min"; annul "$P" "const DEFAULT_HEALTH_CHECK_INTERVAL_MIN = 60" "const DEFAULT_HEALTH_CHECK_INTERVAL_MIN = 30"
echo "== 30: circuito ignorado"; annul "$P" "  if (isInRefreshBackoff(connection, context.nowMs)) return SKIP
  const reason" "  const reason"
echo "== 32: sin aborto"; annul "$P" "  if (name === 'AbortError' || name === 'TimeoutError') return true" "  if (name === 'TimeoutError') return true"
echo "== 33: sin causa"; annul "$P" "  const cause = record.cause instanceof Error ? record.cause.message : ''" "  const cause = ''"
echo "== 34: sin código"; annul "$P" " || NETWORK_ERROR.test(\`\${String(record.code ?? '')} \${String(record.cause?.code ?? '')}\`)" ""
echo "== 35: sin fetch failed"; annul "$P" "|socket hang up|fetch failed\`" "|socket hang up\`"
echo "== 36: nombre de objeto ignorado"; annul "$P" "  const name = error instanceof Error ? error.name : String(record.name ?? '')" "  const name = error instanceof Error ? error.name : ''"
echo "== 37: refresh token vacío se guarda"; annul "$P" "  if (result.refreshToken) update.refreshToken = result.refreshToken" "  update.refreshToken = result.refreshToken"
echo "== 38: expiresIn gana"; annul "$P" "const expiresAt = result.expiresAt || (result.expiresIn" "const expiresAt = (result.expiresIn"
echo "== 39: sin tokenExpiresAt"; annul "$P" "    update.tokenExpiresAt = expiresAt" ""
echo "== 40: circuito no se limpia"; annul "$P" "  if (cleared !== undefined) update.providerSpecificData = cleared" "  if (false) update.providerSpecificData = cleared"
echo "== 41: datos siempre"; annul "$P" "  else if (result.providerSpecificData) update.providerSpecificData = merged" "  else update.providerSpecificData = merged"
echo "== 42: cambio no se detecta"; annul "$P" "  if (current && (current.refreshToken !== attempted.refreshToken || (current.accessToken || null) !== attempted.accessToken)) return" "  if (false) return"
echo "== 43: sólo el refresh cuenta como cambio"; annul "$P" "current.refreshToken !== attempted.refreshToken || (current.accessToken || null) !== attempted.accessToken" "current.refreshToken !== attempted.refreshToken"
echo "== 44: token vigente expira"; annul "$P" "  if (effectiveTokenExpiryMs(current || connection) > nowMs + TOKEN_EXPIRY_BUFFER_MS) {" "  if (false) {"
echo "== 45: sin desactivar a la tercera"; annul "$P" "  if (exhausted) update.isActive = false" ""
echo "== 46: refresh muerto se conserva"; annul "$P" "  if (shouldNullRefreshTokenAfterUnrecoverable(connection.provider)) update.refreshToken = null" ""
echo "== 47: sin código gana el error"; annul "$P" "  const label = result.code || result.error" "  const label = result.error"
echo "== 48: rota sin consumido"; annul "$P" "\`Refresh token \${rotating ? 'consumed' : 'rejected'}" "\`Refresh token \${'rejected'}"
echo "== 49: sin contar el reintento"; annul "$P" "  const retry = expiredRetryCount(connection) + 1" "  const retry = expiredRetryCount(connection)"
echo "== restaurado"; run
