import { afterAll, describe, expect, test } from 'bun:test'
import { chmodSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { BlobLocationError, hostBlobPath, modelBlobOfModelfile, volumeMountpoint } from '../volumeBlobs.js'

const WORKDIR = mkdtempSync(join(tmpdir(), 'volume-blobs-'))
afterAll(() => rmSync(WORKDIR, { recursive: true, force: true }))

const DIGEST = 'b'.repeat(64)

function fakePodman(name: string, body: string): string {
  const path = join(WORKDIR, name)
  writeFileSync(path, `#!/bin/sh\necho "$@" >> '${path}.calls'\n${body}\n`)
  chmodSync(path, 0o755)
  return path
}

describe('volumeMountpoint — `podman volume inspect`', () => {
  test('devuelve el Mountpoint del volumen pedido', async () => {
    const podman = fakePodman('podman-ok', `echo '${WORKDIR}/volume-data'`)
    expect(await volumeMountpoint(podman, 'thyrox-ollama-models')).toBe(`${WORKDIR}/volume-data`)
    expect(readFileSync(`${podman}.calls`, 'utf8')).toBe('volume inspect thyrox-ollama-models --format {{.Mountpoint}}\n')
  })

  test('podman que sale distinto de 0 se rehúsa con su stderr', async () => {
    const podman = fakePodman('podman-missing', 'echo "no such volume" >&2; exit 125')
    await expect(volumeMountpoint(podman, 'ghost')).rejects.toThrow(/ghost.*no such volume/)
  })

  test('una salida vacía no es un punto de montaje', async () => {
    const podman = fakePodman('podman-empty', 'true')
    await expect(volumeMountpoint(podman, 'v')).rejects.toThrow(BlobLocationError)
  })

  test('un binario que no existe se rehúsa nombrándolo', async () => {
    await expect(volumeMountpoint(join(WORKDIR, 'no-podman'), 'v')).rejects.toThrow(/no-podman/)
  })
})

describe('modelBlobOfModelfile — la capa GGUF que declara /api/show', () => {
  test('lee la línea FROM con el blob', () => {
    const modelfile = `# Modelfile generated by "ollama show"\nFROM /root/.ollama/models/blobs/sha256-${DIGEST}\nTEMPLATE """{{ .Prompt }}"""\n`
    expect(modelBlobOfModelfile(modelfile)).toEqual({ containerPath: `/root/.ollama/models/blobs/sha256-${DIGEST}`, sha256: DIGEST })
  })

  test('un FROM que no es un blob sha256 se rehúsa', () => {
    expect(() => modelBlobOfModelfile('FROM qwen2.5:0.5b\n')).toThrow(BlobLocationError)
  })

  test('sin FROM se rehúsa', () => {
    expect(() => modelBlobOfModelfile('TEMPLATE x\n')).toThrow(BlobLocationError)
  })
})

describe('hostBlobPath — del contenedor al volumen en el anfitrión', () => {
  test('el prefijo /root/.ollama se cambia por el punto de montaje', () => {
    expect(hostBlobPath(`/root/.ollama/models/blobs/sha256-${DIGEST}`, '/var/vol/_data')).toBe(`/var/vol/_data/models/blobs/sha256-${DIGEST}`)
  })

  test('una ruta fuera del directorio de modelos montado se rehúsa', () => {
    expect(() => hostBlobPath('/srv/models/blobs/x', '/var/vol/_data')).toThrow(BlobLocationError)
  })
})
