#!/usr/bin/env bash
# Anulaciones de #106d-5b-2: se retira cada mitad de juicio de zed-hosted, xai-oauth y grok-cli.
set -u
T=${T:-/home/user/thyrox}; cd "$T/src/packages/provider"
A="src/accounts"; Z="$A/zed/zedNativeAuth.ts"; ZF="$A/oauth/flows/zedHostedFlow.ts"; X="$A/oauth/flows/xaiOAuthFlow.ts"
G="$A/oauth/flows/grokCliFlow.ts"; GT="$A/grok/grokTokens.ts"; GB="$A/grok/grokBuild.ts"
run() { timeout 120 bun test __tests__/accounts/oauth/zedGrokXaiFlows.test.ts 2>&1 | gawk '/^\(fail\)|^ *[0-9]+ (pass|fail)$/'; }
source "$T/.claude/workbench/mitm-f7h-api-20260928T070339/annul-lib.sh"
echo "== 1: cualquier verificador es una clave"; annul "$Z" "  if (!value.startsWith(PRIVATE_KEY_PREFIX)) throw" "  if (false) throw"
echo "== 2: sin consulta suelta"; annul "$Z" '      url = new URL(`http://127.0.0.1/?${raw.replace(/^\?/, '"''"')}`)' "      throw new Error('Invalid Zed callback URL')"
echo "== 3: sin JSON"; annul "$Z" "    data = JSON.parse(raw) as JsonRecord" "    throw new Error('json')"
echo "== 4: sin el alias token"; annul "$Z" "data.access_token || data.accessToken || data.token" "data.access_token || data.accessToken"
echo "== 5: la organización declarada no gana"; annul "$Z" "  if (explicit) return explicit" "  void explicit"
echo "== 6: sin la organización personal"; annul "$Z" "organizations.find(item => item?.is_personal) || " ""
echo "== 7: el usuario de zed como Bearer"; annul "$Z" '  return `${userId} ${accessToken}`' '  return `Bearer ${accessToken}`'
echo "== 8: cualquier host reusa el puerto local"; annul "$ZF" "    if (!LOOPBACK_HOST.test(new URL(redirectUri).hostname)) return null" "    void 0"
echo "== 9: un usuario caído tumba el login"; annul "$ZF" "        // Sin usuario la cuenta sigue sirviendo: la organización se resuelve al primer uso." "        throw new Error('lookup')"
echo "== 10: sin el login de github como nombre"; annul "$ZF" "name = text(userInfo?.name) || text(userInfo?.github_login)" "name = text(userInfo?.name)"
echo "== 11: xai sin variable no rehúsa"; annul "$X" "      client_id: requireClientId(config)," "      client_id: String(config.clientId),"
echo "== 12: el nonce fijo"; annul "$X" "nonce: randomBytes(NONCE_BYTES).toString('hex')," "nonce: '0'.repeat(32),"
echo "== 13: xai con el verificador corto"; annul "$X" "    pkceVerifierBytes: PKCE_VERIFIER_BYTES," ""
echo "== 14: los espacios como +"; annul "$GB" '`${key}=${encodeURIComponent(value)}`' 'new URLSearchParams({ [key]: value }).toString()'
echo "== 15: xai sin nombre no hay etiqueta"; annul "$X" "        name: identity.name || identity.email," "        name: identity.name,"
echo "== 16: cualquier código de usuario"; annul "$G" "  if (!USER_CODE.test(data.user_code)) throw" "  if (false) throw"
echo "== 17: cualquier esquema"; annul "$G" "  if (url.protocol !== 'https:' && !isLocalHttp) throw" "  if (false) throw"
echo "== 18: caracteres de control admitidos"; annul "$G" "  if (hasControl) throw" "  if (false) throw"
echo "== 19: sin HTTP local"; annul "$G" "  const isLocalHttp = url.protocol === 'http:' &&" "  const isLocalHttp = false &&"
echo "== 20: la respuesta sin URI no es incompleta"; annul "$G" " || typeof data.verification_uri !== 'string')" ")"
echo "== 21: el error sin la descripción"; annul "$G" "typeof data.error_description === 'string' ? data.error_description : 'Grok device authorization failed'" "'Grok device authorization failed'"
echo "== 22: una página que no es JSON queda vacía"; annul "$G" "    return { error: 'invalid_response', error_description: 'xAI returned a non-JSON OAuth response' }" "    return {}"
echo "== 23: el navegador sin cota inferior"; annul "$GT" "    expiresIn: clampTtl(expiresIn)," "    expiresIn,"
echo "== 24: el navegador sin seis horas por defecto"; annul "$GT" "Number.isFinite(tokens.expires_in) ? tokens.expires_in : DEFAULT_TTL_SECONDS" "Number.isFinite(tokens.expires_in) ? tokens.expires_in : 0"
echo "== 25: el principal de equipo no es el usuario"; annul "$GT" "(isTeam || isOrganization ? principalId : claim(payload, 'sub'))" "(claim(payload, 'sub'))"
echo "== 26: el equipo sin su principal"; annul "$GT" "(isTeam ? principalId : claim(payload, 'team_id'))" "(claim(payload, 'team_id'))"
echo "== 27: la organización sin su principal"; annul "$GT" "(isOrganization ? principalId : claim(payload, 'organization_id'))" "(claim(payload, 'organization_id'))"
echo "== 28: el principal distingue mayúsculas"; annul "$GT" "  const type = principalType.toLowerCase()" "  const type = principalType"
echo "== 29: el ámbito activo no se prefiere"; annul "$GT" "preferredScope && keys.includes(preferredScope) ?" "false ?"
echo "== 30: sin expires_at"; annul "$GT" "  if (pasted.expiresAt) {" "  if (false) {"
echo "== 31: sin exp"; annul "$GT" "  } else if (typeof payload?.exp === 'number' && payload.exp) {" "  } else if (false) {"
echo "== 32: lo pegado sin cota inferior"; annul "$GT" "  return clampTtl(expiresIn)" "  return expiresIn"
echo "== 33: el objeto pegado sin su refresco"; annul "$GT" "return bare(record.accessToken, typeof record.refreshToken === 'string' ? record.refreshToken : null)" "return bare(record.accessToken, null)"
echo "== 34: el auth.json sin desenvolver"; annul "$GT" "typeof record.accessToken === 'object' && record.accessToken !== null ? (record.accessToken as JsonRecord) : record" "record"
echo "== 35: la respuesta de servidor como pegado"; annul "$G" "isGrokBuildBrowserTokens(token)" "false"
echo "== 36: el navegador de grok sin verificador largo"; annul "$G" "    pkceVerifierBytes: PKCE_VERIFIER_BYTES," ""
echo "== 37: la URL de verificación completa se ignora"; annul "$G" "typeof data.verification_uri_complete === 'string' ? data.verification_uri_complete : data.verification_uri" "data.verification_uri"
echo "== restaurado"; git -C "$T" status --short -- src/packages/provider/src/accounts; run
