/**
 * Tests for cleanup pure helpers — used in stats-cache file aging.
 *
 * convertFileNameToDate parses the ISO-like timestamp out of a filename
 * generated by `new Date().toISOString().replace(/[:.]/g, '-')` (the
 * stats-aggregate file naming convention).
 *
 * Wrong parse = stale-file detection silently fails (files never get
 * cleaned up → disk fills) or aggressive (current files get deleted).
 */
import { describe, expect, test } from 'bun:test'
import {
  addCleanupResults,
  convertFileNameToDate,
} from '../aggregates/cleanup.js'

describe('addCleanupResults', () => {
  test('combines messages and errors', () => {
    expect(
      addCleanupResults({ messages: 5, errors: 1 }, { messages: 3, errors: 2 }),
    ).toEqual({ messages: 8, errors: 3 })
  })

  test('zeros: identity for the other operand', () => {
    expect(
      addCleanupResults(
        { messages: 0, errors: 0 },
        { messages: 5, errors: 5 },
      ),
    ).toEqual({ messages: 5, errors: 5 })
  })

  test('does not mutate inputs', () => {
    const a = { messages: 1, errors: 1 }
    const b = { messages: 2, errors: 2 }
    addCleanupResults(a, b)
    expect(a).toEqual({ messages: 1, errors: 1 })
    expect(b).toEqual({ messages: 2, errors: 2 })
  })
})

describe('convertFileNameToDate — ISO round-trip', () => {
  test('parses canonical filename format', () => {
    // Format: 2026-04-30T14-30-45-123Z.jsonl → 2026-04-30T14:30:45.123Z
    const date = convertFileNameToDate('2026-04-30T14-30-45-123Z.jsonl')
    expect(date.toISOString()).toBe('2026-04-30T14:30:45.123Z')
  })

  test('strips extension correctly (.split on .)', () => {
    // Documented: filename.split('.')[0] strips extension before parsing.
    const date = convertFileNameToDate('2026-01-01T00-00-00-000Z.json')
    expect(date.toISOString()).toBe('2026-01-01T00:00:00.000Z')
  })

  test('multi-dot extension uses first-dot split', () => {
    // .split('.')[0] takes everything BEFORE first dot. So
    // '2026-04-30T14-30-45-123Z.foo.jsonl' becomes
    // '2026-04-30T14-30-45-123Z'.
    const date = convertFileNameToDate(
      '2026-04-30T14-30-45-123Z.foo.jsonl',
    )
    expect(date.toISOString()).toBe('2026-04-30T14:30:45.123Z')
  })

  test('millisecond zero-padding preserved', () => {
    const date = convertFileNameToDate('2026-04-30T00-00-00-001Z.jsonl')
    expect(date.toISOString()).toBe('2026-04-30T00:00:00.001Z')
  })

  test('invalid format → Invalid Date', () => {
    // No T match → regex no-op → invalid ISO → Invalid Date.
    const date = convertFileNameToDate('not-a-date.jsonl')
    expect(Number.isNaN(date.getTime())).toBe(true)
  })

  test('round-trip: ISO → filename → ISO', () => {
    // Simulate the file-creation path: new Date().toISOString() →
    // replace : and . with - → add extension.
    const original = new Date('2026-04-30T14:30:45.789Z').toISOString()
    const filename = original.replace(/[:.]/g, '-') + 'Z.jsonl'
    // Wait, ISO already ends with Z. Let me redo:
    const filename2 = original.replace(/:/g, '-').replace(/\./g, '-') + '.jsonl'
    const parsed = convertFileNameToDate(filename2)
    expect(parsed.toISOString()).toBe(original)
  })
})
