// Canonical owner is @thyrox/provider/betasConstants.
export * from '@thyrox/provider/betasConstants.js'
// Nombres de valor generados por src/verify/expandStarShims.ts — `bun build` no
// los ve a través de un `export *` externo cuando el shim también es entrada.
export { ADVISOR_BETA_HEADER, AFK_MODE_BETA_HEADER, BEDROCK_EXTRA_PARAMS_HEADERS, CACHE_DIAGNOSIS_BETA_HEADER, CACHE_EDITING_BETA_HEADER, CLAUDE_CODE_20250219_BETA_HEADER, CLI_INTERNAL_BETA_HEADER, CONTEXT_1M_BETA_HEADER, CONTEXT_MANAGEMENT_BETA_HEADER, EFFORT_BETA_HEADER, EXTENDED_CACHE_TTL_BETA_HEADER, FAST_MODE_BETA_HEADER, INTERLEAVED_THINKING_BETA_HEADER, LN_BETA_HEADER, MID_CONVERSATION_SYSTEM_BETA_HEADER, PROMPT_CACHING_SCOPE_BETA_HEADER, REDACT_THINKING_BETA_HEADER, STRUCTURED_OUTPUTS_BETA_HEADER, TASK_BUDGETS_BETA_HEADER, TOKEN_EFFICIENT_TOOLS_BETA_HEADER, TOOL_SEARCH_BETA_HEADER_1P, TOOL_SEARCH_BETA_HEADER_3P, VERTEX_COUNT_TOKENS_ALLOWED_BETAS, WEB_SEARCH_BETA_HEADER } from '@thyrox/provider/betasConstants.js'
